import type { ReactNode } from "react";

export const metadata = {
  title: "SaaS Factory Starter",
  description: "Generated by the AI SaaS Factory",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "system-ui, sans-serif", margin: 0, background: "#0d1117", color: "#e6edf3" }}>
        <main style={{ maxWidth: 720, margin: "0 auto", padding: 24 }}>{children}</main>
      </body>
    </html>
  );
}
